### ISSUE TITLE
Fix igniter

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#1]
not our favorite igniter?

also looks like things are very broken with schematics

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135778312-088190af-5b91-4f7f-bfa0-e05522da4c5b.png)

**Comment by rusefillc** [comment]
let's put a via on A35 and A30 traces

We actually need two of same 6 pos "white" headers on these IGN traces for smart coil conversion
