### ISSUE TITLE
silkscreen URL and QR

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#13]
https://rusefi.com/s/proteus-M73tu

https://github.com/rusefi/rusefi/raw/master/misc/www/s/proteus-M73tu/qr-proteus-M73tu.png

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/138168081-9ab5097a-f958-46ef-b10a-76691d811aa1.png)
