### ISSUE TITLE
Wire both MAF sensors, with a jumper

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#14]
Let's connect both MAF sensors to available analog channels on Proteus

![image](https://user-images.githubusercontent.com/48498823/137057796-c7fdef0f-86f7-4420-bde9-256e175e3178.png)

![image](https://user-images.githubusercontent.com/48498823/137057955-28c4ad2d-b912-4ac4-98b6-498a7ac8c0be.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/138169656-b24eeb45-b67b-430b-850e-050533f2d670.png)
![image](https://user-images.githubusercontent.com/4116383/138170065-4364c678-5313-4611-bb08-8a43b6c15fa0.png)
Only one free AV input on Proteuse
Please close if it is ok
