### ISSUE TITLE
Data readiness

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#5]
This ticket should be assigned to @rusefillc if data input is needed

This ticket should be assigned NOT to @rusefillc if we have data to move forward

**Comment by rusefillc** [comment]
Please place two 134 footprints on the schematics and I will work on pinout data entry

![55mm-between-plastic-rectangles](https://user-images.githubusercontent.com/48498823/134818300-580561b8-f74f-41d5-8667-3b01d0cbc0b8.jpg)

**Comment by rusefillc** [comment]
@Timbelom has entered some basic data

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135771411-82019583-333e-454d-bc83-9c9d60cde16f.png)

**Comment by rusefillc** [comment]
perfect
