### ISSUE TITLE
dual-etb connectors and pedal connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#6]
We need dual ETB both high-current DC output and position sensors

We need single pedal position sensor connector

**Comment by rusefillc** [comment]
Most interesting question is what connectors do we go with

NB1 suggests C240832 for DC motors

![image](https://user-images.githubusercontent.com/48498823/135318625-bd12238b-0745-4317-b251-c13871fb366c.png)

**Comment by Qwerty-OFF** [comment]
C240832 for ETB
C8876 for TPS
C21273 for PPS
![image](https://user-images.githubusercontent.com/4116383/135779355-b48b8e28-622e-4924-aead-9e5bca0e4fff.png)
