### ISSUE TITLE
MAP sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-M73tu-adapter#8]
BMW does not have OEM MAP sensor so we shall add on the adapter

Please attempt a dual footprint: MPX4250 like used on Miata is getting harder to purchase, please add MPXH6400 as second option

need "MAP" silkscreen to distinguish from BARO

(Honda has OEM MAP sensor)

**Comment by rusefillc** [comment]
only one would be soldred on any specific board so combined footprint would be best

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/135924103-779b5909-8ce9-4cdf-994c-eb753a38c0d2.png)
